### ISSUE TITLE
Support functional object?

### ISSUE THREAD

**Issue by findmyway** [pbayer/YAActL.jl#15]
The `Actor` only supports function as `bhv`. It may be useful to remove this restriction to support functional object as argument in some cases.

## To do

remove `func<:Function` restriction from 

- [ ] Actor, 
- [ ] become!, become,
- [ ] exec!,
- [ ] Func,
- [ ] update docs

**Comment by pbayer** [comment]
I assume, you are talking about [function objects](https://en.wikipedia.org/wiki/Function_object#In_Julia) as in

```
julia> mutable struct Accumulator
                  n::Int
          end

julia> function (acc::Accumulator)(n2)
                  acc.n += n2
          end

julia> a = Accumulator(4)
Accumulator(4)

julia> a(5)
9

julia> typeof(a)
Accumulator

julia> a isa Function
false
```

Yes, I see it makes sense to support them in actors. Thank you very much for the proposal.

```
julia> using YAActL

julia> act = Actor(a)
ERROR: MethodError: no method matching Actor(::Accumulator)
....
```

In Julia's `Base` `Task(func)` doesn‘t restrict `func` to `Function`. The docs say that it must be only callable. I think, I can do the same and implement it right away. 

The downside is that it will fail at execution time when the object is not callable. But with improved error handling in 0.3 this should not be a big issue. PS: I could even check with `methods` whether it is callable.

**Comment by pbayer** [comment]
This has been implemented [in issue 8 of Actors](https://github.com/JuliaActors/Actors.jl/issues/8).

Since future versions of `YAActL` will be based on `Actors` I won't work anymore on this issue here.
Please switch to `Actors` for your project. Most stuff from `YAActL` went into it.
